branch-defaults:
  development:
    environment: ut-wcwh
    group_suffix: null
  master:
    environment: ut-wcwh
  production:
    environment: ut-wcwh
environment-defaults:
  ut-wcwh:
    branch: null
    repository: null
global:
  application_name: beiwe-application
  branch: null
  default_ec2_keyname: CC_BEIWE_CLUSTER_KEY
  default_platform: python-2.7
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
